/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioConttroler;
import model.Usuario;
import tools.CaixaDeDialogo;

/**
 *
 * @author guilherme.w1
 */
public class TelaUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form TelaUsuarios
     */
    public TelaUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome_tela_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLogin_tela_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pass1_tela_usuario = new javax.swing.JPasswordField();
        pass2_tela_usuario = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnExcluirUsuario_tela_usuario = new javax.swing.JButton();
        txtExcluir_tela_usuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        txtNome_tela_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNome_tela_usuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Login");

        jLabel4.setText("Senha");

        jLabel5.setText("Confirmar Senha ");

        jLabel6.setText("Cadastro de Usuários");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnExcluirUsuario_tela_usuario.setText("Excluir usuario");
        btnExcluirUsuario_tela_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirUsuario_tela_usuarioActionPerformed(evt);
            }
        });

        txtExcluir_tela_usuarios.setText("Id do usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pass1_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pass2_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtNome_tela_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLogin_tela_usuario, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(jLabel4)))
                                        .addGap(115, 115, 115)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirUsuario_tela_usuario, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtExcluir_tela_usuarios)
                                        .addGap(36, 36, 36))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jButton1)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExcluir_tela_usuarios))
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirUsuario_tela_usuario))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass1_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass2_tela_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean retorno = validarDados();
        
        if(retorno){
            
            Usuario usuario = guardarDados();
            
            UsuarioConttroler objController = new UsuarioConttroler();
            objController.incluir(usuario);
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private Usuario guardarDados(){
        try{
            Usuario objeto = new Usuario();
            
            objeto.setLogin(txtLogin_tela_usuario.getText().trim());
            objeto.setNome(txtNome_tela_usuario.getText().trim());
            objeto.setSenha(pass1_tela_usuario.getText());
            return objeto;
        }catch(Exception e){
            return null;
        }
    }
    
    
    
    private void txtNome_tela_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNome_tela_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNome_tela_usuarioActionPerformed

    private void btnExcluirUsuario_tela_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirUsuario_tela_usuarioActionPerformed
        
        
        
    }//GEN-LAST:event_btnExcluirUsuario_tela_usuarioActionPerformed
    
    private boolean validarDados(){
        
        if(txtNome_tela_usuario.getText().trim().equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um Nome");
            return false;
        }
        if(txtLogin_tela_usuario.getText().trim().equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um Login");
            return false;
        }
        
        int indice = txtLogin_tela_usuario.getText().indexOf(" ");
       if(indice >= 0){
           CaixaDeDialogo.obterinstancia().exibirMensagem("Login sem espaços");
       }
       if(pass1_tela_usuario.getText().trim().equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Senha 1 em branco");
            return false;
        }
       if(pass2_tela_usuario.getText().trim().equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Senha 2 em branco");
            return false;
        }
       if(!pass1_tela_usuario.getText().trim().equals(pass2_tela_usuario.getText())){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Senha 1 em branco");
            return false;
        }
       
       return true;
            
        
        
        /*if(txtLogin_tela_usuario.equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um Login");
            return false;
        }else if(txtNome_tela_usuario.equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe um nome");
            return false;
        }else if(pass1_tela_usuario.equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe uma senha");
            return false;
        }else if(pass2_tela_usuario.equals("")){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Informe uma senha");
            return false;
        }else if(pass1_tela_usuario != pass2_tela_usuario){
            CaixaDeDialogo.obterinstancia().exibirMensagem("Senha um diferente da senha 2");
            return false;
        }
        
            return true;
        */
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirUsuario_tela_usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField pass1_tela_usuario;
    private javax.swing.JPasswordField pass2_tela_usuario;
    private javax.swing.JLabel txtExcluir_tela_usuarios;
    private javax.swing.JTextField txtLogin_tela_usuario;
    private javax.swing.JTextField txtNome_tela_usuario;
    // End of variables declaration//GEN-END:variables
}
